### ISSUE TITLE
request for functionality to judge whether a sequence is chaotic

### ISSUE THREAD

**Issue by HaoLi111** [abarbour/psd#4]
For a 1D map can we have some functions to return a boolean value (TRUE or FALSE)
the function may be named

is.chaotic()

or 

is.quasiPeriodical()

Judging by width of 'peaks' might work. A better idea may be to calculate square of errors when fitting a smoothed (e.g. linear) model to the P[dB] ~ log(frequency) plot. 
Is this achievable?

**Comment by HaoLi111** [comment]
P.S. I know that calculating Lyapunov exponent is way easier. but since properties of Chao (Li-Y or Devaney defn.) is still to be discussed, period detection may show an important aspect. Cheers.

**Comment by HaoLi111** [comment]
I am currently making lots of plots for a chaotic map and rendering animations. Maybe I can try coding this if anyone could tell me where to get the raw data of the first plot shown

I am trying to get a data frame containing 
 P[dB] ~ log(frequency)

similar to the first plot shown below

```
library(SeriesXplorerZoo)
x =SeriesXplorerZoo::Batrachion_Conway1988(10000)/1:10000

library(psd)

x_spc = pspectrum(x,plot=T)



x_est = pilot_spec(x)
plot(x_est)
str(x_est)

png(width =1280,height=720)
x_est = psd::pspectrum(x_ts,plot = T)
dev.off()

```


![Rplot001](https://user-images.githubusercontent.com/32727671/59200216-d6460800-8beb-11e9-906a-ff7445f30c69.png)

@abarbour @jkennel 
Thanks

**Comment by abarbour** [comment]
I'm not quite sure I understand what you're attempting to do. I'm not an expert in analyzing chaotic processes, but it sounds like this is not compatible with a simple TRUE/FALSE decision. I'd suggest you try and develop a standalone package that imports the necessary functions from psd, but has the functionality you're pursuing. Can you clarify what data you're trying to find? If it's the spectrum from `pspectrum`, then you can use the `as.data.frame` method, e.g.: `as.data.frame(pspectrum(rnorm(100)))`

**Comment by HaoLi111** [comment]
@abarbour 
Thanks for your reply. 
I am trying to extract the data for the first plot (the black curve from the plot"Spectral density estimates") (spectral density [dB] with respect to log of frequency). Where are the 2 variable stored in the object returned by pspectrum() ,or how can I get them?


I put a 1D vector (on the code shown was the Batrachion series mentioned by Conway in a speech in 1988, a fractal sequence), to see if it is chaotic (this is just one aspect of chao since defn. of chao is still not generally agreed). 
Generally a 1D sequence with chaotic behavior is not periodic, nor quasi-periodic, so it is expected that on the power spectrum of it, the peaks are "widened" (few or no specific frequency with high energy). We'd expect a chaotic sequence to have a smoother curve of the power spectrum estimates(in dB) in a lot of cases.


I agree that maybe I write some other package to do it. Could you show me where to get the 2 vars ? Many thanks.

H.

**Comment by abarbour** [comment]
```
p <- pspectrum(rnorm(100))
pc <- pgram_compare(p)
```
Gives a list with the raw periodogram results (`'spec'`) and the pspectrum results (`'amt'`):
```
str(pc,1)
#List of 2
# $ spec:List of 16
#  ..- attr(*, "class")= chr "spec"
# $ amt :List of 19
#  ..- attr(*, "class")= chr [1:2] "amt" "spec"
```
So then you can access the content in any way you wish, e.g.:
```
lapply(pc, as.data.frame)
as.data.frame(pc[['spec']])
as.data.frame(pc[['amt']])
```

**Comment by abarbour** [comment]
But I just wanted to point out that the _only_ thing `pgram_compare` is doing is running `stats::spec.pgram` on the same dataset... it's really only meant for its side effects (e.g., plotting) as a diagnostic tool.
