### ISSUE TITLE
Improvement: calculate the cross-spectrum of two timeseries

### ISSUE THREAD

**Issue by sbcalaff** [abarbour/psd#6]
Technically speaking, is it possible to calculate the optimal number of tapers at each frequency for a cross-spectrum of two univariate timeseries?

**Comment by abarbour** [comment]
Yes it is. Recently [(9ec9d84)](https://github.com/abarbour/psd/commit/9ec9d84015381f88718f093b5e0aa53e0fc506db) @jkennel expanded the code to do just this while maintaining computational efficiently. I haven't yet had the time to issue a formal release to CRAN, but will do so soon(ish). In the meantime I encourage you to test out what has been added with the development version:
```
library(remotes)
install_github('abarbour/psd')
```
Here's a silly example:
```
library(psd)
set.seed(1113)
n <- 1000
inp <- rnorm(n) # represents the 'input' to the system
resp <- inp + runif(n) # represents the 'response' of the system
io <- cbind(inp, resp)

p <- pspectrum(io)

# Because io is a multi-dimensional array, 'p' should contain coherence, admittance and phase 

layout(matrix(1:3,1))
with(p,{
  plot(freq, coh, ylim=c(0,1), type='l', main='Coherence')
  plot(freq, Mod(transfer), ylim=c(0,1), type='l', main='Admittance (Gain)')
  plot(freq, phase, ylim=pi*c(-1,1), type='l', main='Phase')
})
```

**Comment by gmgeorg** [comment]
Are you planning on releasing this version to CRAN anytime soon?  

background: I am the author of the [ForeCA](https://github.com/gmgeorg/ForeCA) package, which relies heavily on multivariate (cross) spectral density estimation.  I have relied previously on the **sapa** R package, but unfortunately **ifultools** package -- and thus **sapa** -- have been removed from CRAN recently. While looking for a good alternative for the excellent `sapa::SDF()` I came across **psd** and this issue in particular.  I tried the test code above with the dev version here (1.2.1) and it does exactly what I need for ForeCA (return a 3D complex-valued array with the multivariate cross-spectrum).

**Comment by abarbour** [comment]
Thanks for asking. I too am feeling the impact of the sapa/ifultools
removal as I was also relying on SDF in kitagawa
<https://cran.r-project.org/package=kitagawa>, so this is good motivation
to push version 2 out the door to CRAN.

Thanks for testing the dev version and letting me know that it works for
you. The cran maintainers have given me a deadline of June 23rd to fix
kitagawa or risk having it removed too, so I'll be working on this
diligently.

Is ForeCA in danger of removal? If so, is it before the 23rd?

**Comment by gmgeorg** [comment]
Apparently my grace period ended earlier, so it has been removed already last week (despite **ifultools** having fixed the issues; its just that the maintainer handover on their side was not handled in time I think, hence CRAN removed it).

the current ForeCA version on github works w/o SDF by just using [**astsa**](https://cran.r-project.org/web/packages/astsa/index.html) package; but it seems that **psd** would be a closer/better replacement of `sapa::SDF` so I was checking in if I should release the ForeCA update now, or just wait if psd is getting on CRAN anytime soon.

**Comment by abarbour** [comment]
So far the new additions pass all of our checks. We're just trying to wrap
up a new vignette discussing some basic usage before submitting to CRAN. I
expect it will only be a few more days.

**Comment by abarbour** [comment]
Version 2.0 is on CRAN now (https://cran.r-project.org/package=psd). Note that the capabilities are all there, but in the interest of expedience (e.g., to meet the 'kitagawa' package deadline), we released it with with a few known issues that need to be taken care of. These are all minor ones related to methods like `plot`, `as.data.frame`, etc, as well as some documentation. So look out for minor version bumps soon. Regardless, comments and issues welcome!
