### ISSUE TITLE
Namespace error with psd::pspectrum() and psdcore.default()

### ISSUE THREAD

**Issue by gmgeorg** [abarbour/psd#9]
I run into a namespace issue when using `psd::pspectrum`:
```
data(magnet, package = "psd")
x <- magnet$clean
spec <- psd::pspectrum(x, plot = TRUE)
```
gives error on
```
Error in psdcore.default(ntaper = 7, AR = FALSE, preproc = FALSE, refresh = TRUE,  : 
  !is.null(ops) is not TRUE
```
Same issue is described here at end of document:
https://towardsdatascience.com/attach-packages-mindfully-in-r-b9c8151b3fb4

**Comment by abarbour** [comment]
Thanks for catching this! I was setting options in `.onAttach` when I should've been using `.onLoad`; fixed in v2.1 as of ([afe0a64d](https://github.com/abarbour/psd/commit/afe0a64d125187b66ac7b2aa2377e928378e701d))

**Comment by gmgeorg** [comment]
Thanks for quick fix. Is this pending on CRAN?  background: I could successfully integrate psd into ForeCA, but CRAN submission checks fail on this error.

**Comment by abarbour** [comment]
Got a little sidetracked last week -- sorry -- but I'll push it out in
hopefully a day or two. I'll then try to look more carefully into the issue
with frequencies you raised separately.

**Comment by abarbour** [comment]
Ok, 2.1 is on CRAN now (source only, binaries still being built).
